### ISSUE TITLE
Add Author Data file

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/apibusters.com#4]
We need to have an `_data/authors.yml`which contains something like:

``` yaml
philsturgeon:
    name: Phil Sturgeon
    twitter: philsturgeon
    clarify_url: https://clarify.fm/dskhakd
```
The author can then be specified as a page variable in a post’s frontmatter:

``` md
---
title: sample post
author: philsturgeon
---

Bla bla article
```

``` liquid
{% assign author = site.data.authors[page.author] %}
<a rel="author"
  href="{{ author.twitter }}"
  title="{{ author.name }}">
    {{ author.name }}
</a>
```
